import type { CakeOption } from "@/content/cake-maker/schema";

/**
 * Fillings — the stripes between the sponge layers.
 *
 * TODO(content): confirm the menu. TODO(pricing): all deltas are placeholders.
 */
export const fillingOptions: CakeOption[] = [
  {
    id: "swiss-buttercream",
    label: { en: "Swiss Meringue Buttercream" },
    description: { en: "Silky and not too sweet. The default for a reason." },
    taxonomySlug: "swiss-buttercream",
    priceDelta: 0,
    pricePerServing: 0,
    allergens: ["dairy", "egg"],
    requires: [],
    featured: true,
    swatch: "#fdf4e3",
    visual: { role: "filling", fill: "#fdf4e3" },
  },
  {
    id: "cream-cheese",
    label: { en: "Cream Cheese" },
    description: { en: "Tangier, and it cuts through a rich sponge." },
    taxonomySlug: "cream-cheese",
    priceDelta: 0,
    pricePerServing: 0.25,
    allergens: ["dairy"],
    requires: [],
    featured: false,
    swatch: "#fbf6ec",
    visual: { role: "filling", fill: "#fbf6ec" },
  },
  {
    id: "ganache",
    label: { en: "Chocolate Ganache" },
    description: { en: "Dense and glossy. Pairs with almost everything." },
    taxonomySlug: "ganache",
    priceDelta: 0,
    pricePerServing: 0.5,
    allergens: ["dairy", "soy"],
    requires: [],
    featured: true,
    swatch: "#4b2f22",
    visual: { role: "filling", fill: "#4b2f22" },
  },
  {
    id: "fresh-cream",
    label: { en: "Chantilly Cream" },
    description: { en: "Light and barely sweet. Best eaten the same day." },
    taxonomySlug: "fresh-cream",
    priceDelta: 0,
    pricePerServing: 0,
    allergens: ["dairy"],
    requires: [],
    featured: false,
    swatch: "#fffdf8",
    visual: { role: "filling", fill: "#fffdf8" },
  },
  {
    id: "fruit-compote",
    label: { en: "Fruit Compote" },
    description: { en: "Seasonal fruit, cooked down. Tell us which fruit." },
    taxonomySlug: "fruit-compote",
    priceDelta: 0,
    pricePerServing: 0.5,
    allergens: [],
    requires: [],
    featured: false,
    swatch: "#b8384f",
    visual: { role: "filling", fill: "#b8384f" },
  },
  {
    id: "salted-caramel",
    label: { en: "Salted Caramel" },
    description: { en: "Cooked dark, with flaked salt." },
    taxonomySlug: "salted-caramel",
    priceDelta: 0,
    pricePerServing: 0.75,
    allergens: ["dairy"],
    requires: [],
    featured: true,
    swatch: "#c98b3e",
    visual: { role: "filling", fill: "#c98b3e" },
  },
];
